ALTER TYPE "SettlementTestMode" RENAME VALUE 'DEMO' TO 'EVIDENCE_ONLY';
ALTER TYPE "SettlementTestMode" RENAME VALUE 'SHADOW' TO 'PROVIDER_OBSERVED';
ALTER TYPE "SettlementTestMode" RENAME VALUE 'LIVE_TEST' TO 'CONTROLLED_PILOT';

ALTER TABLE "Settlement"
ALTER COLUMN "test_mode" SET DEFAULT 'PROVIDER_OBSERVED';
